id: sh.crystal.crystal
name: Crystal
version: 0.5.1
description: the open source code generator for every language, library and platform
repository: https://github.com/crystal/crystal
author:
  name: Chris Tate
  email: chris@crystal.sh
  url: http://crystal.sh
copyright: 2015 Crystal
modules:
  sh.crystal.default: v0.1.0
  sh.crystal.gitignore: v0.1.0
  sh.crystal.npm: v0.1.0
  sh.crystal.readme: v0.1.0
  sh.crystal.travis: v0.1.0
imports:
  gitignore: sh.crystal.gitignore.GitignoreGenerator
  npm: sh.crystal.npm.ConfigGenerator
  readme: sh.crystal.readme.ReadmeGenerator
  travis: sh.crystal.travis.ConfigGenerator
exports:
  ConfigSchematic:
    schema: config.yml
    type: schematic
outputs:
  - generator: gitignore
    spec:
      items:
        - .DS_Store
        - node_modules/
  - generator: npm
    spec: npm.yml
  - generator: readme
    spec:
      name: $name
      description: $description
      version: $version
      logo:
        image: http://crystal.sh/images/crystal.svg
        text: $name
        url: http://crystal.sh
      badges:
        - image: https://badge.fury.io/js/crystal.svg
          text: npm version
          url: http://badge.fury.io/js/crystal
        - image: https://travis-ci.org/crystal/crystal.svg?branch=master
          text: Build Status
          url: https://travis-ci.org/crystal/crystal
  - generator: travis
    spec:
      language: node_js
      node_js:
      - '0.12'
scripts:
  build:
    - sudo npm install
  run:
    - sudo npm install
  test:
    - test
