name: Crystal
version: 0.15.0
description: code generator for every language, framework and platform
repository: https://github.com/crystal/crystal
author:
  name: Chris Tate
  email: chris@crystal.sh
  url: http://crystal.sh
copyright: 2015 Crystal
imports:
  crystal/authors: ~0.2.5
  crystal/gitignore: ~0.1.1
  crystal/npm: ~0.2.5
  crystal/readme: ~0.2.2
  crystal/travis: ~0.1.0
exports:
  ConfigSchematic:
    schema: config.yml
    type: schematic
outputs:
  - generator: gitignore.GitignoreGenerator
    spec:
      items:
        - .DS_Store
        - node_modules/
        
  - generator: npm.PackageGenerator
    spec: npm.yml
    
  - generator: readme.ReadmeGenerator
    spec:
      name: $name
      description: $description
      version: $version
      logo:
        image: http://crystal.sh/images/crystal.svg
        text: $name
        url: http://crystal.sh
      badges:
        - image: https://badge.fury.io/js/crystal.svg
          text: npm version
          url: http://badge.fury.io/js/crystal
        - image: https://travis-ci.org/crystal/crystal.svg?branch=master
          text: Build Status
          url: https://travis-ci.org/crystal/crystal
        - image: https://badges.gitter.im/Join%20Chat.svg
          text: Join the chat at https://gitter.im/crystal/crystal
          url: https://gitter.im/crystal/crystal?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge
          
  - generator: travis.ConfigGenerator
    spec:
      language: node_js
      node_js:
      - '0.12'
scripts:
  build:
    - sudo npm install
  run:
    - sudo npm install
  test:
    - test