name: Crystal
version: 0.13.3
description: code generator for every language, framework and platform
repository: https://github.com/crystal/crystal
author:
  name: Chris Tate
  email: chris@crystal.sh
  url: http://crystal.sh
copyright: 2015 Crystal
modules:
  authors.file: v0.1.0
  git.ignore: v0.1.0
  npm.package: v0.1.0
  readme.md: v0.1.0
  travis.config: v0.1.0
imports:
  authors: authors.file.Generator
  gitignore: git.ignore.Generator
  npm: npm.package.Generator
  readme: readme.md.Generator
  travis: travis.config.Generator
exports:
  ConfigSchematic:
    schema: config.yml
    type: schematic
outputs:
  - generator: gitignore
    spec:
      items:
        - .DS_Store
        - node_modules/
  - generator: npm
    spec: npm.yml
  - generator: readme
    spec:
      name: $name
      description: $description
      version: $version
      logo:
        image: http://crystal.sh/images/crystal.svg
        text: $name
        url: http://crystal.sh
      badges:
        - image: https://badge.fury.io/js/crystal.svg
          text: npm version
          url: http://badge.fury.io/js/crystal
        - image: https://travis-ci.org/crystal/crystal.svg?branch=master
          text: Build Status
          url: https://travis-ci.org/crystal/crystal
        - image: https://badges.gitter.im/Join%20Chat.svg
          text: Join the chat at https://gitter.im/crystal/crystal
          url: https://gitter.im/crystal/crystal?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge
  - generator: travis
    spec:
      language: node_js
      node_js:
      - '0.12'
scripts:
  build:
    - sudo npm install
  run:
    - sudo npm install
  test:
    - test
