name: Autocode
version: 1.0.6
description: the ultimate developer platform
repository: https://github.com/crystal/autocode
author:
  name: Chris Tate
  email: chris@autocode.run
  url: https://autocode.run
copyright: 2015 Crystal
imports:
  crystal/authors: ~0.3.3
  crystal/bower: ~0.4.1
  crystal/git: ~0.2.0
  crystal/grunt: ~0.3.1
  crystal/npm: ~0.4.0
  crystal/readme: ~0.5.1
  crystal/travis: ~0.3.0
exports:
  ConfigSchema:
    schema:
      type: object
      properties:
        author:
          type: object
          properties:
            name:
              title: Name
              type: string
            email:
              title: Email
              type: string
            url:
              title: URL
              type: string
        copyright:
          title: Copyright
          type: string
        description:
          description: This project's description.
          title: Description
          type: string
        exports:
          type: object
          additionalProperties:
            type: object
            properties:
              description:
                type: string
              engine:
                type: string
              example:
                type: string
              helper:
                type:
                  - string
                  - object
                additionalProperties:
                  type: string
              processor:
                type: string
              generator:
                type: string
              schema:
                type:
                  - object
                  - string
              spec:
                type:
                  - array
                  - object
                  - string
              type:
                required: true
                type: string
        imports:
          type: object
          additionalProperties:
            type:
              - string
              - object
            properties:
              aliases:
                type: object
                additionalProperties:
                  type: string
              version:
                type: string
        name:
          description: This project's name.
          title: Name
          type: string
        version:
          description: This project's version.
          title: Version
          type:
            - number
            - string
    type: schema
outputs:
  - generator: bower.ConfigGenerator
    spec:
      directory: app/lib/components
  
  - generator: bower.PackageGenerator
    spec:
      name: autocode
      description: $description
      main: lib/autocode.js
      dependencies:
        CodeMirror: 5.7.0
        formulator: 0.6.2
        google-diff-match-patch-js: 1.0.0
        jquery: 2.1.4
        jquery-cookie: 1.4.1
        js-yaml: 3.4.2
        marked: 0.3.5
        zeroclipboard: 2.2.0
  
  - generator: git.GitignoreGenerator
    spec:
      items:
        - .DS_Store
        - app/lib/components/
        - app/lib/scripts
        - node_modules/
  
  - generator: grunt.GruntfileGenerator
    spec:
      loadNpmTasks:
        - grunt-contrib-concat
        - grunt-contrib-watch
      registerTask:
        default:
          - concat
      config:
        pkg: package.json
        concat:
          options:
            separator: ;
          dist:
            src:
              - app/src/scripts/autocode.js
              - app/src/scripts/autocode/*.js
              - app/src/scripts/*/**
            dest: app/lib/scripts/autocode.js
        watch:
          files:
            - app/src/scripts/autocode.js
            - app/src/scripts/*/**
          tasks:
            - concat
  
  - generator: npm.NPMIgnoreGenerator
    spec:
      items:
        - cli/src
        - src
  
  - generator: npm.PackageGenerator
    spec: npm.yml
    
  - generator: readme.ReadmeGenerator
    spec:
      logo:
        image: https://rawgit.com/crystal/autocode/master/.autocode/image.svg
        text: $name
        url: https://autocode.run
      showTableOfContents: true
      sections:
        - name: intro
          title: Introduction
          content: |
            Autocode is the ultimate developer platform.
            
            It combines **metaprogramming**, **code generation**, **code automation** and a **[powerful user interface](https://app.autocode.run)** to help you:
            
            - Quickly build full stacks: frontends, backends and everything in between.
            - Instantly add **anything** to your stack: frameworks, package managers, build tools, scripts and more.
            - Go **beyond project scaffolding** - Autocode is with you through the life of your projects to help you innovate with every iteration.
            - Generate code for **any language and framework** and automate the development of apps, websites, APIs and any other software.
            
            Learn more [here](https://autocode.run).
        - name: install
          title: Install
          content: |
            Choose an Interface:
            
            - [Command-Line](#install-cli)
            - [JavaScript (Node.js)](#install-js)
            
            <a name="install-cli"></a>
            
            ## Command-Line
            
            Use [npm](https://npmjs.com) or [Homebrew](https://brew.sh) to install the Command-Line interface of Autocode:
            
            ```sh
            npm install autocode -g # most popular
            brew install autocode # mac only
            ```
            
            <a name="install-js"></a>
            
            ## JavaScript (Node.js)
            
            Use [npm](https://npmjs.com) to install the JavaScript interface of Autocode:
            
            ```sh
            npm install autocode
            ```
        - name: tour
          title: Take a Tour
          content: |
            Try Autocode online here:
            
            [https://app.autocode.run/#tour](https://app.autocode.run/#tour)

        - name: docs
          title: Documentation
          content: |
            View Autocode's Official Documentation here:

            [https://crystal.readme.io](https://crystal.readme.io)
  - generator: travis.ConfigGenerator
    spec:
      language: node_js
      node_js:
      - '0.12'
scripts:
  build:
    - description: Install Node.js via nvm.
      command: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.29.0/install.sh | bash
    - description: Install Bower via npm.
      command: npm install bower -g
    - description: Install CoffeeScript via npm.
      command: npm install coffee-script -g
    - description: Install Forever via npm.
      command: npm install forever -g
    - description: Install http-server via npm.
      command: npm install http-server -g
    - description: Install Grunt CLI via npm.
      command: npm install grunt-cli -g
    - description: Install npm Modules.
      command: npm install
    - description: Install bower Modules.
      command: bower install
    - description: Compile Library.
      command: coffee --compile --output lib/ src/
    - description: Compile CLI Library.
      command: coffee --compile --output cli/lib/ cli/src/
  run:
    - description: Run web server for Autocode app.
      command: forever start app/app.js
  stop:
    - description: Stop web server for Autocode app.
      command: forever stopall
  test:
    - description: Test Autocode.
      command: npm test